# Generated by Django 4.2 on 2024-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
